name: Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export UID/GID for Compose
        run: |
          echo "UID=$(id -u)" >> "$GITHUB_ENV"
          echo "GID=$(id -g)" >> "$GITHUB_ENV"

      - name: Build the project
        run: docker compose -f docker-compose.yml run --rm balatro sh -c "make -j$(nproc)"

      - name: Compose down
        if: always()
        run: docker compose -f docker-compose.yml down -v || true
